language: node_js

sudo: required

node_js:
  - "8.11.1"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.8

before_install:
  - export CXX="g++-4.8"

install:
  - cd smart-contracts/ethereum && npm install 


script:
  - npm run ganache &
  - npm run truffle test